apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sample-repo
  namespace: fluxcd-demo
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/RevanthChowdary1708/eks-project