apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sample-app
  namespace: fluxcd-demo
spec:
  interval: 15m
  path: "./fluxcd/manifests/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: sample-repo