apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
    project: fluxcd-demo
  namespace: fluxcd-demo
spec:
  selector:
    matchLabels:
      app: sample-app
      project: fluxcd-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: sample-app
        project: fluxcd-demo
    spec:
      containers:
      - name: sample-app
        image: sairevanthchowdarych/eks-flux-app:e6ab8bba
        ports:
        - containerPort: 80